# Numpy

---

###### --> A powerful N-dimenssional array object
###### --> Sopisticated (brodcasting) function
###### --> Tools for integrating c/c++ and fortan code
###### --> Useful lenear algebra

---

### 1-D

In [2]:
l1=[1,2,3,4]
import numpy as np
np.array(l1)                 

array([1, 2, 3, 4])

### 2-D

In [3]:
l2=[[1,2,3],[4,5,6],[7,8,9]]
np.array(l2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
l2[1]

[4, 5, 6]

In [5]:
l2[1][0]

4

In [7]:
# l2[1,0]          ......its typeerror   

In [8]:
l2[2][2]

9

In [10]:
l2.pop()             #.... dot after enter only (tab) show the modules
                     #.... curser with in the function enter (shift+tab) show the content

[4, 5, 6]

## Arange

In [12]:
a2=np.arange(10)
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(2,6)

array([2, 3, 4, 5])

In [14]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

## Zeros and Ones

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

## Linespace

In [21]:
np.linspace(1,5,8)              #....starting '1' ending '5' only show '8' numbers

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

## Eye

##### creates an identity matrix

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 

###### Uniform distibution (0,1)

### Rand

In [23]:
np.random.rand(2)               # one peramiter means only rows

array([0.45015067, 0.05696627])

In [25]:
np.random.rand(2,3)           # two peramiters means both rows and coloumns

array([[0.23707192, 0.6081435 , 0.06959302],
       [0.43850066, 0.39648061, 0.89562765]])

### Randn

In [26]:
np.random.randn(2)

array([ 0.30236476, -1.00558645])

In [28]:
np.random.randn(2,3)

array([[ 0.23335652, -0.45743587,  1.06029882],
       [-0.74965309,  1.05503315,  0.8937922 ]])

### Randint

##### random integer


In [29]:
np.random.randint(1,100)

88

#####  import directly

In [30]:
from numpy.random import randint

In [31]:
randint(1,20)

11

In [32]:
randint(1,20,4)

array([10, 11, 10,  2])

## Reshape

In [35]:
za=np.arange(25)
za

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
za.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
za.reshape(5,5, order='F')                 #...f means fortan

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [40]:
zb=za.reshape(5,5, order='F')  
zb

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [41]:
zb.max()

24

In [42]:
zb.min()

0

In [44]:
za.argmax()

24

In [45]:
zb.argmin()

0

In [58]:
zc=np.random.randint(0,50,10)
zc

array([ 2, 19, 26, 37, 11, 15,  9, 10, 12, 11])

In [59]:
zc.max()

37

In [60]:
zc.min()

2

In [61]:
zc.argmax()

3

In [62]:
zc.argmin()

0

## shapes

In [63]:
zc.shape

(10,)

In [64]:
zb.shape

(5, 5)

In [65]:
zd=np.arange(100)
zd

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [66]:
zd.shape

(100,)

In [67]:
zd.reshape(2,50)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [3]:
a1=np.arange(2,25)
a1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24])

In [4]:
a1[1]

3

## Indexing

In [7]:
a1=np.arange(5,25)
a1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [8]:
a1[0]

5

In [9]:
a1[:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [10]:
a1[0:5]

array([5, 6, 7, 8, 9])

In [11]:
a1[4:]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [12]:
a1[:-1]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23])

In [14]:
# a1[]=55

In [16]:
a2=a1[0:10]
a2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
a2[:5]=55

In [18]:
a2

array([55, 55, 55, 55, 55, 10, 11, 12, 13, 14])

In [20]:
a3=a1.copy()
a3

array([55, 55, 55, 55, 55, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [21]:
a3[:4]=20
a3

array([20, 20, 20, 20, 55, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [22]:
a1

array([55, 55, 55, 55, 55, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [23]:
a3

array([20, 20, 20, 20, 55, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [24]:
a2

array([55, 55, 55, 55, 55, 10, 11, 12, 13, 14])

In [30]:
z1=np.array(([5,10,15],[20,25,30],[35,40,45]))
z1

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
z1[1][1]

25

In [32]:
z1[1:-1,1:-1]

array([[25]])

In [33]:
z1[2][2]

45

In [36]:
z1[2:,2:]

array([[45]])

## Array Operators

In [37]:
a1=np.arange(1,11)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
a1>6

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [40]:
bol=a1>6
bol

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [41]:
a1[bol]

array([ 7,  8,  9, 10])

In [42]:
a1[a1<6]

array([1, 2, 3, 4, 5])

## Reshape and Slicing

In [45]:
m1=np.arange(1,51).reshape(5,10)
m1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [47]:
a=m1[2:-1,5:-1]
a

array([[26, 27, 28, 29],
       [36, 37, 38, 39]])

In [48]:
a[1,1]

37

In [49]:
a[1][1]

37

In [50]:
a[1]

array([36, 37, 38, 39])

In [54]:
a1=np.arange(0,11)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
a1+a1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [56]:
a1*a1

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [58]:
a1.sum()

55

In [60]:
a1.max()

10

## Numpy Exercise